puppet_forge.gemspec
This is license format is also recommended by rubygems.org
http://spdx.org/licenses/Apache-2.0
=> Use SPDX License format

puppet_forge.gemspec, spec/spec_helper.rb, spec/unit/forge/v3/base_spec.rb, spec/unit/forge/v3/module_spec.rb, spec/unit/forge/v3/release_spec.rb, spec/unit/forge/v3/user_spec.rb, spec/unit/her/lazy_accessors_spec.rb, spec/unit/her/lazy_relations_spec.rb
Before this commit, if a user got a newer version of Her it could cause
Rspec tests to fail. With this commit, users are required to use the
version of Her that works with the module.
The commit also updated the Rspec tests to work with Rspec 3.x and
specifies this requirement in the gemspec.
=> (CODEMGMT-279) Specify versions for Her and Rspec.

lib/puppet_forge/v3/base.rb, lib/puppet_forge/v3/base/paginated_collection.rb, spec/integration/forge/v3/module_spec.rb, spec/integration/forge/v3/release_spec.rb, spec/integration/forge/v3/user_spec.rb, spec/unit/forge/v3/base/paginated_collection_spec.rb, spec/unit/forge/v3/base_spec.rb, spec/unit/forge/v3/module_spec.rb, spec/unit/forge/v3/release_spec.rb
There should be 55 RSpec tests with 6 failures. 
* 4 failures are because the requests are not made lazily.
* 1 failure is because we have not added downloading back into the gem after removing Her.
* 1 is because the PMT Acceptance Forge is running on old API code.
=> (CODEMGMT-296) Add PaginatedCollection ORM for where request

lib/puppet_forge.rb, lib/puppet_forge/connection.rb, lib/puppet_forge/connection/connection_failure.rb, lib/puppet_forge/error.rb, lib/puppet_forge/tar.rb, lib/puppet_forge/tar/mini.rb, lib/puppet_forge/unpacker.rb, lib/puppet_forge/v3.rb, lib/puppet_forge/v3/base.rb, lib/puppet_forge/v3/metadata.rb, lib/puppet_forge/v3/release.rb, puppet_forge.gemspec, spec/integration/forge/v3/module_spec.rb, spec/integration/forge/v3/release_spec.rb, spec/integration/forge/v3/user_spec.rb, spec/spec_helper.rb, spec/unit/forge/connection/connection_failure_spec.rb, spec/unit/forge/connection_spec.rb, spec/unit/forge/tar/mini_spec.rb, spec/unit/forge/tar_spec.rb, spec/unit/forge/unpacker_spec.rb, spec/unit/forge/v3/metadata_spec.rb, spec/unit/forge/v3/module_spec.rb, spec/unit/forge/v3/release_spec.rb, spec/unit/forge/v3/user_spec.rb
Before this commit, the puppet_forge gem was not able to downlaod
releases. With this commit, the gem is able to download and verify the
MD5 of a release.
The find method now raises a Faraday::ResourceNotFound instead of
returning nil when the resource does not exist.
=> (CODEMGMT-297) Integrate ModuleRelease from r10k

CHANGELOG.md, README.md, lib/puppet_forge/error.rb, lib/puppet_forge/v3/release.rb, lib/puppet_forge/version.rb
This commit:
- adds a forbidden release error and the use of that error when downloading a release.  These were added to the shared puppet_forge code before r10k was made dependent on the puppet_forge gem.
- updates the version number to 2.1.0 and the CHANGELOG and README.
- fixes a problem with ReleaseForbidden error call.
=> (CODEMGMT-307) Update puppet_forge gem for use with r10k

lib/puppet_forge/v3/release.rb
Before this commit, the error message coming back from a missing module
relese was unhelpful. This corrects it back to what was expected. ("The
module release blah-1.0.0 does not exist on
https://forgeapi.puppetlabs.com")
=> (RK-170) Bad error on missing release.

.gitignore, README.md, Rakefile, lib/puppet_forge.rb, lib/puppet_forge/connection/connection_failure.rb, lib/puppet_forge/error.rb, lib/puppet_forge/lazy_relations.rb, lib/puppet_forge/unpacker.rb, lib/puppet_forge/v3/metadata.rb, lib/puppet_forge/v3/release.rb, locales/config.yaml, puppet_forge.gemspec
This adds the i18n library and externalizes error message strings
for i18n. A 'set_locale' method has also been added to allow the
user of the puppet_forge gem to set its locale
=> (CODEMGMT-725) Externalize strings for i18n

puppet_forge.gemspec
Because of 1.x dependency on the Her gem, it also depends on
activesupport. On June 30, activesupport 5 was released which only
supports ruby >= 2. Her's dependency on activesupport allows this
gem to pull in activesupport 5, which breaks this gem in ruby < 2.
=> Specify activesupport version more granularly.

spec/unit/forge/connection_spec.rb
The proxy setting of `"http://proxy.example.com:3128"` would sometimes carry over to the integration tests.
Run with the `--seed 27590` to run in an order that can produce the error.
``` ruby
bundle exec rspec --seed 27590 --color
```
=> Fix connection test for some random orders

CHANGELOG.md, lib/puppet_forge/util.rb, spec/unit/forge/util_spec.rb
This commit passes through the Semantic::Version.valid? method so that
r10k can drop a dependency on semantic_puppet.
=> (RK-306) Add helper method in puppet_forge for valid semantic version.

puppet_forge.gemspec
This allows for people who need a higher version of faraday for other
gems to be able to meet that requirement without forcing existing users
to upgrade their current version.
=> Allow for higher versions of faraday

lib/puppet_forge/v3/release.rb, spec/unit/forge/v3/release_spec.rb
Since calling any MD5 method can cause an immediate segfault on
FIPS-enabled systems, we need to provide a way to avoid that call
altogether. This change adds a param to the PuppetForge::V3::Release
class' #verify method that allows the caller to disable fallback to MD5
in cases where the SHA-256 checksum is not available.
=> (FORGE-360) Add `allow_md5` param to Release#verify method

.travis.yml
Previously, every cell in the matrix was trying to deploy at the end,
this should change it to only do one deploy after every cell of the test
matrix passes.
Also, the api_key was previously encrypted for travis-ci.org whereas the
current integration is using travis-ci.com which requires a different
encrypted value.
=> (MAINT) Move deploy to distinct build stage and update api_key

puppet_forge.gemspec
Users discovered an issue where faraday 0.13.1 does not correctly
respect proxy settings unless they are set in the environment. This gem
sets them programmatically, and in 0.13.1, that is ignored. This caused
issues with proxies configured for r10k. This commit updates the max
allowed version of faraday to inclue 0.14.0, where this issue was fixed.
=> (PE-27712) Allow faraday to go to version 0.14.0

.github/workflows/ruby-rspec.yml
These don't pass, and since puppet 5 (the oldest supported puppet
series) ships with ruby 2.4, we'll stop testing with 2.3.
=> (MAINT) Remove ruby 2.3 github checks

puppet_forge.gemspec
faraday_middleware 0.13.1 got released on 2019-02-04.
=> allow faraday_middleware 0.13.X

.github/workflows/ruby-rspec.yml
Ruby 2.7 got released some time ago and the first distributions start to
ship it. We should therefore also run the testsuite on that version.
=> Add Ruby 2.7 to GitHub Actions testmatrix

lib/puppet_forge/connection/connection_failure.rb, spec/unit/forge/connection/connection_failure_spec.rb
Recently, libcurl started sending timeout error codes instead of the
more generic "couldn't connect". The typheous adapter that we use with
Faraday surfaces these as `Faraday::TimeoutError` instead of
`Faraday::ConnectionFailed`. But we still want similar logging when the
request times out, so this commit updates our error handling to also
catch the `TimeoutError`.
=> (RK-358) Handle TimeoutErrors from Faraday

puppet_forge.gemspec
Increases the upper bound of the faraday dependency to anything under 0.18. Not sure we can allow version 1.0 yet, but this should hold us for a while.
=> (MAINT) Allow newer versions of faraday

puppet_forge.gemspec
Allow use of faraday_middleware v0.14.0.
https://rubygems.org/gems/faraday_middleware
warning seen:
> /Users/aerickson/git/ronin_puppet/vendor/ruby/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
The warning can also been seen on master with 2.7 (or a PR like https://github.com/puppetlabs/forge-ruby/pull/81/checks?check_run_id=459193126).
fixed upstream in https://github.com/lostisland/faraday_middleware/pull/189
=> (MAINT) Allow newer versions of faraday_middleware

lib/puppet_forge/v3/base.rb
Getting a ton of these errors:
> ./Users/aerickson/git/forge-ruby/lib/puppet_forge/v3/base.rb:59: warning: deprecated Object#=~ is called on URI::HTTP; it always returns nil
They can be seen when inspecting the "Build and test with Rspec" step of the tests on master (or another PR like https://github.com/puppetlabs/forge-ruby/pull/80/checks?check_run_id=459172469) with ruby 2.7.
Running rspec locally this gets rid of the messages (when running ruby 2.7).
=> fix ruby 2.7 warning about "deprecated Object#=~"

README.md, lib/puppet_forge/connection.rb, spec/unit/forge/connection_spec.rb
Authorized requests to the Forge require an authorization header of
"Bearer \<api-key\>". This changes the connection process so that if a
user has set `PuppetForge::Connection.authorization` to something that
looks like a Forge API key (a 64-character hex string), it automatically
prepends the "Bearer " string. This will not take effect if the user
has already prepended "Bearer " themselves, or if the authorization
value doesn't fit the expected key format.
Also updates the README with basic information on authorization.
=> (PF-2437) Prepend 'Bearer' string to authorization

.github/workflows/ruby-rspec.yml, lib/puppet_forge/connection.rb, lib/puppet_forge/connection/connection_failure.rb, puppet_forge.gemspec
It does not attempt to support Faraday 1.x as well because dependency wise it would be impossible to pull in the correct middleware. That is why a hard switch was made.
See individual commits for details.
Replaces https://github.com/puppetlabs/forge-ruby/pull/98, https://github.com/puppetlabs/forge-ruby/pull/97 & https://github.com/puppetlabs/forge-ruby/pull/96.
This would be a major version bump.
=> Move to Faraday 2.x, which requires Ruby 2.6+

README.md, lib/puppet_forge/error.rb, lib/puppet_forge/v3/release.rb, spec/unit/forge/v3/release_spec.rb
The purpose of this change is to introduce upload functionality to the forge ruby client.
We currently push to the forge in pdk but have a custom method for handling it. It would be nice to consolidate and use the client for all forge operations.
The initial commits for this PR were cherry-picked from #65.
=> (CONT-643) Add upload method functionality

lib/puppet_forge/v3/base.rb
The Forge API expects a space separated list of endorsements. This feels
weird from the perspective of the consumer of a library. I'd expect that
implementation detail to be abstracted away.
This patch allows endorsements to be specified as either the space
separated list or as an array.
=> Allows the user to search by an array of endorsements

lib/puppet_forge/v3/module.rb, spec/unit/forge/v3/module_spec.rb
While 026e0c1f467a6edc1e40d3827840fe3b123bef66 did add the exception class, it wasn't used. This avoids leaking an implementation detail.
Technically this is backwards incompatible, since it requires users to change their code. It could make PuppetForge::ModuleNotFound inherit from Faraday::ResourceNotFound, but that stil leaks the implementation detail. It could however be split into two releases: one minor to do this + inherit and make it not inherit in a major release.
=> Raise ModuleNotFound if a module is not found

README.md
This PR was originally to drop support for Ruby 2.4, but most of that was already covered in this PR: https://github.com/puppetlabs/forge-ruby/pull/99. After speaking with Jesse, I made a few small changes to the README that were previously overlooked in that PR.
=> (PF-2540) Updating README

lib/puppet_forge/lru_cache.rb
r10k content_synchronizer uses Forge v3 API when installing a module: https://github.com/puppetlabs/r10k/blob/4.0.0/lib/r10k/module/forge.rb#L95 https://github.com/puppetlabs/r10k/blob/4.0.0/lib/r10k/module/forge.rb#L128 https://github.com/puppetlabs/r10k/blob/4.0.0/lib/r10k/module/forge.rb#L176
r10k uses a thread pool to install the modules, therefore the Forge v3 API calls have to be thread safe, and so does the LruCache class used to cache API responses.
If LruCache is left not thread safe, the same error as reported in r10k issue #979 happens.
https://github.com/puppetlabs/r10k/issues/979
=> Make Digest subclass lookup thread-safe in lru_cache

README.md
Update README.md for gem release process
Add any additional context about the problem here. 
Mention any related issues or pull requests.
=> Update README.md for gem release process
